---
- hosts: localhost
  tasks:
  - name: create storage account for function apps
    azure_rm_storageaccount:
      resource_group: zhijzhao3
      name: azfunccistor66
      account_type: Standard_LRS

  - name: create basic function app
    azure_rm_functionapp:
      resource_group: zhijzhao3
      name: azfunzzjzzj
      storage_account: azfunccistor66

