---
- hosts: localhost
  roles:
  - { role: Azure.azure_preview_modules }
  tasks:
  - name: create storage account for function apps
    azure_rm_storageaccount:
      resource_group: zhijzhao
      name: azfunccistor66
      account_type: Standard_LRS


