---
- hosts: localhost
  tasks:
  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: zhijzhao3
      name: testVnet
      address_prefixes: "10.0.0.0/16"

  - name: Add subnet
    azure_rm_subnet:
      resource_group: zhijzhao3
      name: testSubnet
      address_prefix: "10.0.1.0/24"
      virtual_network: testVnet

  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: zhijzhao3
      allocation_method: Static
      name: testPublicIP

  - name: Create load balancer
    azure_rm_loadbalancer:
      resource_group: zhijzhao3
      name: testLB
      public_ip_address_name: testPublicIP
      natpool_frontend_port_start: 50000
      natpool_frontend_port_end: 50119
      natpool_backend_port: 22
      natpool_protocol: Tcp

  - name: Create VMSS
    azure_rm_virtualmachine_scaleset:
      resource_group: zhijzhao3
      name: testVMSS
      vm_size: Standard_DS1_v2
      admin_username: testuser
      ssh_password_enabled: true
      admin_password: "Password1234!"
      capacity: 2
      virtual_network_name: testVnet
      subnet_name: testSubnet
      load_balancer: testLB
      upgrade_policy: Manual
      tier: Standard
      managed_disk_type: Standard_LRS
      os_disk_caching: ReadWrite
      image:
        offer: CoreOS
        publisher: CoreOS
        sku: Stable
        version: latest
      data_disks:
        - lun: 0
          disk_size_gb: 64
          caching: ReadWrite
          managed_disk_type: Standard_LRS
  